Вправа 2. Вводиться число n. Розставити 1 та 0 у шаховому
порядку, починаючи з 1 в матриці розміром n×n, використовуючи
слайсінг.

In [1]:
%%time
import numpy as np
#Task 1.2.1
def create_chessboard_matrix(n):
    chessboard = np.zeros((n, n), dtype=int)
    chessboard[1::2, ::2] = 1
    chessboard[::2, 1::2] = 1
    return chessboard

print(create_chessboard_matrix(10))

[[0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]]
CPU times: total: 31.2 ms
Wall time: 68.5 ms


In [2]:
%%time
#Task 1.2.2
def create_chessboard_matrix(n):
    chessboard = [[0] * n for _ in range(n)]
    for i in range(n):
        for j in range(n):
            if (i + j) % 2 == 1:
                chessboard[i][j] = 1
    return chessboard


for row in  create_chessboard_matrix(10):
    print(row)

[0, 1, 0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
CPU times: total: 0 ns
Wall time: 0 ns


Вправа 4. Вводяться числа n і m. Вивести масив розміру n×m, в
якому у першому рядку (рядок з нулевим індексом) йдуть числа від 0
до m–1, а всі інші елементи матриці дорівнюють 0.

In [3]:
%%time
#Task 1.4.1
import numpy as np

def generate_matrix_numpy():

    #m, n = map(int, input("Введіть m та n через пробіл: ").split())
    m=3
    n=4
    matrix = np.zeros((n, m), dtype=int)

    matrix[0, :] = np.arange(m)

    print("Згенерована матриця:")
    print(matrix)

generate_matrix_numpy()

Згенерована матриця:
[[0 1 2]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
CPU times: total: 0 ns
Wall time: 0 ns


In [4]:
%%time
#Task 1.4.2

def generate_matrix_iterator():

    #m, n = map(int, input("Введіть m та n через пробіл: ").split())
    m=3
    n=4
    matrix = []

    matrix.append(list(range(m)))

    for _ in range(1, n):
        matrix.append([0] * m)

    print("Згенерована матриця:")
    for row in matrix:
        print(row)

generate_matrix_iterator()

Згенерована матриця:
[0, 1, 2]
[0, 0, 0]
[0, 0, 0]
[0, 0, 0]
CPU times: total: 0 ns
Wall time: 0 ns


Вправа 5. Вводиться число n. Вивести масив розміру n×n, в
якому в рядках з парними індексами стоять 1, а в інших – 0.

In [20]:
%%time
import numpy as np
#Task 1.5.1
def create_array_with_ones(n):
    array = np.zeros((n, n), dtype=int)
    array[::2, :] = 1
    return array

print(create_array_with_ones(10))

[[1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0]]
CPU times: total: 0 ns
Wall time: 0 ns


In [24]:
%%time
#Task 1.5.2
def create_array_with_ones(n):
    matrix = [[0] * n for _ in range(n)]

    for i in range(n):
        for j in range(n):
            if i % 2 == 0:
                matrix[i][j] = 1

    return matrix

for row in create_array_with_ones(10):
    print(row)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
CPU times: total: 0 ns
Wall time: 0 ns


Вправа 8. З клавіатури вводиться масив. Підрахувати в ньому
кількість нульових та ненульових елементів.

In [8]:
%%time
import numpy as np
#Task 1.8.1
def count_zeros_nonzeros(array):
    zeros_count = np.count_nonzero(array == 0)
    nonzeros_count = np.count_nonzero(array != 0)
    return zeros_count, nonzeros_count

try:
    input_array = np.array(list(map(int, input("Введіть масив елементів через пробіл: ").split())))

    zeros, nonzeros = count_zeros_nonzeros(input_array)

    print(f"Кількість нульових елементів: {zeros}")
    print(f"Кількість ненульових елементів: {nonzeros}")

except ValueError:
    print("Некоректний ввід. Будь ласка, введіть числа через пробіл.")

Введіть масив елементів через пробіл:  2 2 2 0


Кількість нульових елементів: 1
Кількість ненульових елементів: 3
CPU times: total: 0 ns
Wall time: 2.85 s


In [9]:
%%time
#Task 1.8.2
def count_zeros_nonzeros(array):
    zeros_count = sum(1 for element in array if element == 0)
    nonzeros_count = sum(1 for element in array if element != 0)
    return zeros_count, nonzeros_count

try:
    input_array = list(map(int, input("Введіть масив елементів через пробіл: ").split()))

    zeros, nonzeros = count_zeros_nonzeros(input_array)

    print(f"Кількість нульових елементів: {zeros}")
    print(f"Кількість ненульових елементів: {nonzeros}")

except ValueError:
    print("Некоректний ввід. Будь ласка, введіть числа через пробіл.")

Введіть масив елементів через пробіл:  2 2 2 0


Кількість нульових елементів: 1
Кількість ненульових елементів: 3
CPU times: total: 15.6 ms
Wall time: 2.73 s


Вправа 9. Вводиться число n. Створити масив значень від n до 0.

In [10]:
%%time
import numpy as np
#Task 1.9.1
def create_array_from_n_to_zero(n):
    return np.arange(n, -1, -1)

print(create_array_from_n_to_zero(10))

[10  9  8  7  6  5  4  3  2  1  0]
CPU times: total: 0 ns
Wall time: 0 ns


In [11]:
%%time
#Task 1.9.2
def create_array_from_n_to_zero_iterative(n):
    result_array = []
    for i in range(n, -1, -1):
        result_array.append(i)
    return result_array


print(create_array_from_n_to_zero_iterative(10))

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
CPU times: total: 0 ns
Wall time: 0 ns


Вправа 12. Створити масив одиниць розміром n×n та створити в
ньому «рамку», що утворюється з 0.

In [12]:
%%time
import numpy as np
#Task 1.12.1
def create_array_with_frame(n):
    array = np.zeros((n, n), dtype=int)

    array[1:-1, 1:-1] = 1
    return array

print(create_array_with_frame(10))

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 0 0 0 0 0 0 0 0 0]]
CPU times: total: 0 ns
Wall time: 0 ns


In [13]:
%%time
#Task 1.12.2
def create_array_with_frame_iterative(n):
    array = [[0] * n for _ in range(n)]

    for i in range(1, n - 1):
        for j in range(1, n - 1):
            array[i][j] = 1

    return array

for row in create_array_with_frame_iterative(10):
     print(row)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 1, 1, 1, 1, 1, 1, 1, 1, 0]
[0, 1, 1, 1, 1, 1, 1, 1, 1, 0]
[0, 1, 1, 1, 1, 1, 1, 1, 1, 0]
[0, 1, 1, 1, 1, 1, 1, 1, 1, 0]
[0, 1, 1, 1, 1, 1, 1, 1, 1, 0]
[0, 1, 1, 1, 1, 1, 1, 1, 1, 0]
[0, 1, 1, 1, 1, 1, 1, 1, 1, 0]
[0, 1, 1, 1, 1, 1, 1, 1, 1, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
CPU times: total: 0 ns
Wall time: 0 ns


Вправа 13. Розмістити на полі 8×8 нулі та одиниці в шахматному
порядку, використовуючи функцію повторення (*).

In [14]:
%%time
import numpy as np
#Task 1.13.1
def create_chessboard_array(size):
    chessboard = np.tile([[0, 1], [1, 0]], (size // 2, size // 2))
    return chessboard[:size, :size]

print(create_chessboard_array(8))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
CPU times: total: 0 ns
Wall time: 0 ns


In [15]:
%%time
#Task 1.13.2
def create_chessboard_array_iterative(size):
    chessboard = []
    for i in range(size):
        row = []
        for j in range(size):
            value = 0 if (i + j) % 2 == 0 else 1
            row.append(value)
        chessboard.append(row)
    return chessboard


for row in create_chessboard_array_iterative(8):
      print(row)

[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
CPU times: total: 15.6 ms
Wall time: 1 ms


Вправа 15. Заповнити парні стовпчикі матриці розміром n×n
одиницями, а непарні – нулями.

In [19]:
%%time
import numpy as np
#Task 1.15.1
def fill_matrix(n):
    matrix = np.zeros((n, n), dtype=int)
    matrix[:, 0::2] = 1  
    return matrix


print(fill_matrix(10))

[[1 0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1 0]]
CPU times: total: 0 ns
Wall time: 0 ns


In [18]:
%%time
#Task 1.15.2
def fill_matrix_iterative(n):
    matrix = [[0] * n for _ in range(n)]

    for i in range(n):
        for j in range(n):
            if j % 2 == 0:
                matrix[i][j] = 1

    return matrix


for row in fill_matrix_iterative(10):
      print(row)

[1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
[1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
[1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
[1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
[1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
[1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
[1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
[1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
[1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
[1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
CPU times: total: 0 ns
Wall time: 0 ns


2. Розв’язати систему алгебраїчних рівнянь за допомогою
формул Крамера і виконати перевірку за допомогою:
a) матричного множення;
b) оберненої матриці;
c) функції numpy.lin.alg.sol
e().

\begin{cases}
x_2 - 3x_3 + 4x_4 &= -5 \\
x_1 - 2x_3 + 3x_4 &= -4 \\
3x_1 + 2x_2 - 5x_4 &= 12 \\
4x_1 + 3x_2 - 5x_3 &= 5 \\
\end{cases}

In [25]:
# Task 2
import numpy as np
def solve_system(matrix_A, vector_B):
    det_A = np.linalg.det(matrix_A)

    solution = []

    for i in range(len(vector_B)):
        temp_matrix = np.copy(matrix_A)

        temp_matrix[:, i] = vector_B.copy()

        det_temp = np.linalg.det(temp_matrix)

        solution.append(det_temp / det_A)

    return np.array(solution)


def check_solution(matrix_A, vector_B, solution):
    result = np.dot(matrix_A, solution)

    print("Перевірка розв'язку:")
    print("Матриця A * Розв'язок:")
    print(result)
    print("Вектор B:")
    print(vector_B)


def check_solution_inverse(matrix_A, vector_B, solution):
    inverse_A = np.linalg.inv(matrix_A)
    result_inverse = np.dot(inverse_A, vector_B)

    print("Перевірка розв'язку за допомогою оберненої матриці:")
    print("Обернена матриця A:")
    print(inverse_A)
    print("Обернена матриця A * Вектор B:")
    print(result_inverse)


def check_solution_numpy_solve(matrix_A, vector_B):
    result_solve = np.linalg.solve(matrix_A, vector_B)

    print("Перевірка розв'язку за допомогою numpy.linalg.solve():")
    print("Розв'язок за допомогою solve():")
    print(result_solve)


def compare_solutions(solution1, solution2, solution3):
    if np.allclose(solution1, solution2) and np.allclose(solution1, solution3):
        print("Всі розв'язки ідентичні.")
    else:
        print("Розв'язки відрізняються.")



def task_SLE():
    try:
        matrix_A = np.array([
            [0, 1, -3, 4],
            [1, 0, -2, 3],
            [3, 2, 0, -5],
            [4, 3, -5, 0]
        ], dtype=np.float64)

        vector_B = np.array([-5, -4, 12, 5], dtype=np.float64)


        solution = solve_system(matrix_A, vector_B)

        print("Розв'язок системи:")
        print(solution)

        check_solution(matrix_A, vector_B, solution)

        check_solution_inverse(matrix_A, vector_B, solution)

        check_solution_numpy_solve(matrix_A, vector_B)



    except Exception as e:
        print(f"Помилка виконання: {str(e)}")

task_SLE()

Розв'язок системи:
[ 1.  2.  1. -1.]
Перевірка розв'язку:
Матриця A * Розв'язок:
[-5. -4. 12.  5.]
Вектор B:
[-5. -4. 12.  5.]
Перевірка розв'язку за допомогою оберненої матриці:
Обернена матриця A:
[[ 0.          0.83333333  0.5        -0.33333333]
 [ 1.25        0.          1.         -0.75      ]
 [ 0.75        0.66666667  1.         -0.91666667]
 [ 0.5         0.5         0.5        -0.5       ]]
Обернена матриця A * Вектор B:
[ 1.  2.  1. -1.]
Перевірка розв'язку за допомогою numpy.linalg.solve():
Розв'язок за допомогою solve():
[ 1.  2.  1. -1.]


3. Обчислити значення матричного виразу
а) з використанням універсальних функцій бібліотеки NumPy.
b) за допомогою ітеративних конструкцій (з використанням
циклів, спискових включень тощо).
с) для обох випадків підрахувати час виконання скрипту та
зробити висновок.
Порівняти всі рішення за допомогою функції numpy.allclose().

\begin{align*} (A^2 - B^2) * (A + B) \end{align*}


\begin{equation}
  \mathbf{A} = \begin{bmatrix}
    7 & 2 & 0 \\
    -7 & -2 & 1 \\
    1 & 1 & 0 \\
  \end{bmatrix}
\end{equation}



\begin{equation}
  \mathbf{B} = \begin{bmatrix}
    0 & 2 & 3 \\
    1 & 0 & -2 \\
    3 & 1 & 1 \\
  \end{bmatrix}
\end{equation}

In [29]:
%%time
#Task 3.1
import numpy as np
def task_3_numpy():
    A = np.array([[7, 2, 0],
                   [-7, -2, 1],
                   [1, 1, 0]])

    B = np.array([[0, 2, 3],
                   [1, 0, -2],
                   [3, 1, 1]])

    result = ((A*A) - (B*B)) * (A+B)

    print(result)

task_3_numpy()

[[ 343    0  -27]
 [-288   -8    3]
 [ -32    0   -1]]
CPU times: total: 0 ns
Wall time: 0 ns


In [28]:
%%time
#Task 3.2
def plus_matrix(matrix_a, matrix_b):
    result = []
    for i in range(len(matrix_a)):
        row = []
        for j in range(len(matrix_a[0])):
            row.append(matrix_a[i][j] + matrix_b[i][j])
        result.append(row)
    return result

def subtract_matrix(matrix_a, matrix_b):
    result = []
    for i in range(len(matrix_a)):
        row = []
        for j in range(len(matrix_a[0])):
            row.append(matrix_a[i][j] - matrix_b[i][j])
        result.append(row)
    return result

def multiply_matrix(matrix_a, matrix_b):
    result = []
    for i in range(len(matrix_a)):
        row = []
        for j in range(len(matrix_b[0])):
            sum = 0
            for k in range(len(matrix_b)):
                sum += matrix_a[i][k] * matrix_b[k][j]
            row.append(sum)
        result.append(row)
    return result

A = [[7, 2, 0],
    [-7, -2, 1],
    [1, 1, 0]]

B = [[0, 2, 3],
    [1, 0, -2],
    [3, 1, 1]]

A2=multiply_matrix(A,A)
B2=multiply_matrix(B,B)
A2subB2=subtract_matrix(A2,B2)
AplusB=plus_matrix(A,B)
result = multiply_matrix(A2subB2,AplusB)

for row in result:
    print(row)

[138, 88, 68]
[-154, -100, -78]
[-14, -16, -12]
CPU times: total: 0 ns
Wall time: 0 ns
